### ISSUE TITLE
TypeError. $('#drop').dropdown() not working

### ISSUE THREAD

**Issue by rubyblackforce** [mattgaudio/mythic-rails#1]
![Screenshot from 2019-06-11 05-21-42](https://user-images.githubusercontent.com/51629359/59260086-f89a4e80-8c08-11e9-8b4b-44c94e911288.png)

Some problem in jquery loading.

**Comment by mattgaudio** [comment]
Thanks for reporting. I'll look into it.

**Comment by mattgaudio** [comment]
I removed a couple lines the error is gone.

**Comment by rubyblackforce** [comment]
ya i did run yarn.oh great!
